### PR TITLE
Bash: Simplest parser of connected devices

### PR DESCRIPTION
**Pull request by denanko**
PR with second task (hwdetect).

### CODE REVIEW

**Review by alexposukhov — CHANGES_REQUESTED** [review]
Actually this script does not detect hot plug,
please add module which is responsible for hot plug detection

**Comment by alexposukhov** [comment]
> Bash: Simplest parser of connected devices

>Nothing more.
Please add detailed description

**Comment by denanko** [comment]
Can I reopen it?

**Comment by denanko** [comment]
Changes were implemented

**Comment by alexposukhov** [comment]
Please add tag to "Add hot plug detection" commit according to project requirements.

**Comment by denanko** [comment]
Done

**Review by alexposukhov — APPROVED** [review]

**Pull request merged**
